[package]
name = "connect"
version = "0.0.2"
authors = ["Sachandhan Ganesh <sachan.ganesh@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
async-channel = "1.4.0"
async-std = { version = "1.6.2", features = ["tokio02", "unstable"] }
async-tls = { version = "0.9.0", default-features = false, features = ["client", "server"]}
async-trait = "0.1.39"
bytes = "0.5.5"
dashmap = "3.11.10"
futures = "0.3.8"
log = "0.4"
protobuf = "2.18.1"
rustls = "0.18.0"

[build-dependencies]
protobuf-codegen-pure = "2.18.1"
